import ToastProvider from "../ToastProvider";
import { poppins } from "../fonts";
import "../globalstyles/globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={poppins.className}>
      <body className="globalpadding">
        <ToastProvider>{children}</ToastProvider>
      </body>
    </html>
  );
}
